import logging  # logging lib (terminal & file)
import sys      # to stop script execution on case of error


# get logger with current name
log = logging.getLogger(__name__)


########################################################################################################################
def do_check(list_param: list[dict]) -> None:
    is_key_ConversionSoftware = ["ConversionSoftware" in dic for dic in list_param]
    if not all(is_key_ConversionSoftware):
        log.error(f"at least one .json do not have \"ConversionSoftware\" field")
        sys.exit(1)

    ConversionSoftware = [dic['ConversionSoftware'] for dic in list_param]
    is_dcm2niix = [content == "dcm2niix" for content in ConversionSoftware]
    if not all(is_dcm2niix):
        log.error(f"at least one .json was not generated by \"dcm2niix\"")
        sys.exit(1)


########################################################################################################################
def decisiontree(list_param: list[dict]) -> str:

    # checks
    do_check(list_param)

    # extract useful parameters for the decision tree
    Modality             = [dic['Modality'            ]                 for dic in list_param]
    Manufacturer         = [dic['Manufacturer'        ]                 for dic in list_param]
    PulseSequenceDetails = [dic['PulseSequenceDetails'].rsplit("%_")[1] for dic in list_param]
    MRAcquisitionType    = [dic['MRAcquisitionType'   ]                 for dic in list_param]


    return ""
